name: Ouput
on: workflow_dispatch
jobs:
  Ouput:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github context
        run: echo "${{ toJSON(github) }}"
      - name: Get current date
        run: echo "MY_DATE=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
      - name: Echo date
        run: echo ${{ env.MY_DATE }}
