name: Ouput
on: workflow_dispatch
jobs:
  Ouput:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github context
        run: echo "${{ toJSON(github) }}"
      - name: Set Time Variable
        run: |
          echo date >> ${TIME}
      - name: Print Time
        run: echo ${TIME}