name: Ouput
on: workflow_dispatch
jobs:
  Ouput:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github context
        run: echo "${{ toJSON(github) }}"
      - name: Echo Repository name
        run: echo "$GITHUB.REPOSITORY"